[cursor]
	style = { shape = "Beam", blinking = "Off" }
	vi_mode_style = { shape = "Beam", blinking = "Off" }

[colors]
	[colors.primary]
		foreground = "#D0D0D0"
		background = "#000000"

[font]
    normal = { family = "Hack Nerd Font", style = "Normal" }
    bold = { family = "Hack Nerd Font", style = "Bold" }
    italic = { family = "Hack Nerd Font", style = "Italic" }
    bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
	size = 12.0

[window]
	padding = {x = 5, y = 5}
	dynamic_padding = true
    dynamic_title = true
    blur = true
    startup_mode = "Maximized"

[terminal]
    shell = "/bin/zsh"
