#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PROMPT_COMMAND='PS1_CMD1=$(__git_ps1 "(%s)")'; PS1='\[\e[91m\]\u\[\e[96m\][\w]\[\e[92m\][${PS1_CMD1}]\n\[\e[91m\]\\$\[\e[0m\] '
if [ -f $HOME/.config/utilidadesYSistema/scripts/aliasShell ]; then
    source $HOME/.config/utilidadesYSistema/scripts/aliasShell
fi
cd() {
    builtin cd "$@"
    ls --color=auto
}


