#Esto ejecuta startx al toque dps de iniciar sesión desde tty
if [[ -z $DISPLAY && $XDG_VTNR -eq 1 && $(tty) == /dev/tty1 ]]; then
   if [ -f ~/.bashrc ]; then
        source ~/.bashrc
   fi
    export PATH=$PATH:/usr/local/go/bin
   /bin/startx
fi
