if [[ -z $DISPLAY && $XDG_VTNR -eq 1 && $(tty) == /dev/tty1 ]]; then
    if [ -f /home/marcosgatica/.zshrc ]; then
        source /home/marcosgatica/.zshrc
    fi
    export PATH=$PATH:/usr/local/go/bin
    /bin/startx
fi
