#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap          14

bspc config top_padding 26
bspc config right_padding 0
bspc config left_padding 0 
bspc config bottom_padding 0

bspc config split_ratio          1
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config focused_border_color "#FF0000"
bspc config active_border_color "#cc0000"
bspc config presel_feedback_color "#ff5555"

