#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config focused_border_color "#00FFFD"
bspc config active_border_color "#ffb86c"
bspc config presel_feedback_color "#ff5555"
bspc rule -a '*' state=floating

