for config_file in split(glob('~/.vim/config/*.vim'), '\n')
  execute 'source' config_file
endfor
colorscheme gruvbox
syntax enable
filetype plugin indent on
highlight Normal guibg=#000000 ctermbg=0
highlight NonText guibg=#000000 ctermbg=0
highlight LineNr guibg=#000000 ctermbg=0
highlight SignColumn guibg=#000000 ctermbg=0
highlight EndOfBuffer guibg=#000000 ctermbg=0
