github.com:
    users:
        marcosgatica2003:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: marcosgatica2003
