#!/bin/bash

nadia="
OOOOOOO00000000000000000000000000000OOOOOOOOOOOOOOO0000000000OOOOOOOOOOOOkkkkOOOOO0OOO00OO00000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKXXKKKKKKKK000OOO
OOOOOOO000000000000000000000000000000OOOOOOOOOOOOOO000000000000OOOOOOOkOOOOOOOOOOO00OOO00000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXKKXXXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK00000OOO
OOOOOOO0000000000000000000000000000000OOOOOOOOOOOOO000000000000OOOOOkkkOOOOOOOOOOO00000000000000000000000000O00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXKKKKKKKKKKXXXXXXXXXXXXXXKKKKKKKKKKKKKKKK00OOOOOxxx
OOOOOOO00000000000000000000000000000000OOOOOOOOOOOO00000000000OOOOOOOOOO00000OOOOOO000000000000OOO0000OOOOkkO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXKKKKKKKKKKKXXXXXXXXXXXXXKKKKKKKKKKKKKKK000Okkkkxdd
OOOOOOOOO0000000000000000000000000000000OOOOOOOOOOO000000000OOOO000000000000OOOOOOOOOO0000OOOkkkkkkxxxxxxddxkOO00KKKK0KKKKKKK00000000KKKKKKKKKKKKXXXXKKKKKKKKKKKKXXXXXXXXXXXXXXKKKKXXXKKXKK000OOkxddddoo
OOOOOOOOOO0000000000000000000000000000000OOOOOOOOO00000000OOOOOO0000000000000OOOOOOO000000OkkxxddddddddoodddxxxxxkxxxdxxxxxxxxddxxxxkkOO0000000KKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXKKKKXXXXKK0OOkkxxdoolllo
OOOOOOOOOO0000000000000000000000000000000OOOOOOOO0000OOOOOOO0000000000000000000OOOOOkOOkkxxddooooooooooollllllccc:::::ccllllloodxxxxxxxxkkOOOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKXXK0OOkdddddollllll
OOOOOOOOOO0000000000000000000000000000O000OOOOOOOO00OOkkOOOO00KKKKKKK0000000000OOkxddxxxxxddddddoooooooolc::::;;;;;;::cccllooddxxkkkkkkkkkkkkkOO0000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXK0kkxollolllcccccc
OOOOOOOOOO00000000000000000000000000000000OOOOOOOOOOOkkkOOOOOOO000000000K00000Okkxxxxxddxxxxdoollcc:::;;;;;;;;;;;;;::cclllodxxxxxxkkkkkOkkkkkkkkkkOO000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Oxdolccccccc:::::
OOOOOOOOOO000000000000000000000000000000000OOOOOOOOOkkkOOOOOkkkkkkkkkOOOO0KKOxdxxxxxkkkkxdocc::;;;;;,,,;;,,,,;;;;:::cclllloooodxxxxxxxkkkkkkkkxddoddkO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKOkxdolc::::::::::::
OOOOOOOOOO00000000000000000000000000000000000OOOOOOOOOOOOOOOkkkkkkkkkkOOOOkxddoodxxxxdoc:;;;;;;,,,,,,,,,,;,,;;;:::::ccccccccclodddxxxxxxddddddoooollloxkOOO000KKKKKKK0000000000K00K0Oxdlllc:::::;;;;;:::
OOOOOOOOOO000000000000000000000000000000K000000OOOOOOOOOOOOOkkkkkkkkkkkkkkxxddxxkkdl::;;;;;;;,;,,,,;;;;;;;;;;;:ccccc:ccccllloooddddddddoollloooooddoollooddxxkkkOOkxxxxkkOkkkkkOOOOOxolccc:;;;;;;;;;;::c
OOOOOOOOOOOO000000000000000000000000000000000000OOOOOOkOOOOOkkkkkkkkkkkxdxxxxxxolc:;;;;;;;,,,,,,,,,,,,,,;;;;;:cllllccccc::::::ccccclloodddddddolooodddoolccccllllllllodkOOkdoloxxxxxdl:::::;;;;;;;;;;:cl
OOOOOOOOOOOOO0000000000000000000000000000000000K00OOOOkkOOkkkkkxxxxkOOkddxxdolc;;;;;,,,,,,,,,,,,,,;;;;;;;;:::cc:::::;;;,,,;;;;;;::ccclllooooollccc::ccloolc::cclcccloddoooooooooddddo:;;;;;;;;;;;;;;;:cl
OOOOOOOOOOOOO0000000000000000000000000000000000KK00000OOOOOkkkkkkOO0Okdooolc:;;;;;;,,,,,',,,,,,,;;;;;;;::ccc::;;,,,,,,,,,;;;;::::cllllcc:::::::::;;,,;::cllc::ccc:clodolcc::coddooolc:;,;;;;;;;;;;;;;:cl
OOOOOOOOOOOOO0000000000000000000000000000000000KKK0K000OOkkkkkOkkxxdlc:cc:;;;,;;;,,,,,,,'',,,;;;;::::::::;;,,,,,,,,,,',,;;;;;::::ccclccc:;;,,,,,,,;;,,;;:ccc:;;;;;::cllllc:;;:cllllc::;,,,,,,,,,;;;::ccl
OOOOOOOOOOOOO000000000000000000000000000000000KKKKKKKKK0000Okxxddooc:;::;;;;;,,,,,,,'',,,,,;;;:;;;;;;;;;;,,,,,,,,',,,,,,,,,;;;;;;,,,,,,,,,,,'''''',,,,;::cc:;;;;;;;;::cccc::;;::::cc:;;,,,,,,,;;;:cclllo
OOOOOOOOOOOOO00000000000000000000000000000000KKKKKKKKKKKKKKKK0000xoc;;;;;;;;,,,,,,''',,,;;;;;;:;;;,,,,,,,,,,'''''''''',,''',,,,,'''''''''''''''''',,,,;::cc:;;;;,,,,;;;::::::;;;;;;:;;;;;,,,,,;;:ccllood
OOOOOOOOOOOOO00000000000000000000000000000000KKKKKKKKKKK000KKK0kdl:;;;;;;;,,,,,,,,,,,,,;;;;;;;;;;,,,,,,''''''''''''''''''''''''''''..''''''''''''',;;;;:clc::;,,,''',,,;;,,,,,,,,,,,,;;;;;;;;;;::ccllood
OOOOOOOOOOOOO00000000000000000000000000000000KKKKKKKKKKKKKK0Okdl:;;;;;,,,,,,,,,,,,,,,,,;;;,,,,,,''''''''''''''''''''''''''''''''''''''''',,,,,,,,,;;::ccllcc::;,,'''''',,,'',,''''''',,,,,,;;;:::cclllod
OOOOOOOOOOOOO0000000000000000000000000000000000KKKKKKKKKK00ko:;;;;;;;,,,,,,,,,,,,,;;;;;,,''',,,''''......''''''''''''''''''''''''''',,,;;;;;;;;,;:::cclooolccc:;,,'''''.''...''''''''''',,,,;;::cclllood
OOOOOOOOOOOOO00000000000000000000000000000000000KKKKKKKK0kdc:;;;;;;,,,,,,,,',,,,,;;;;,,''''',''''.....................'''''',,,,,,,;;;:::::::::::cclloddddolllcc;,,'................''''',,,;::ccclloodx
OOOOOOOOOOOOO000000000000000000000000000000000000KKKK00Odc::;;;;;,,,,,,,,''',,,;;;;,,'''''''''''....................''''',,,;;:::::::cccccccccclllooodddxdddoollc;,''...............'''''',,;:ccclloddxx
OOOOOOOOOOOOO0000000000000000000000000000000000KK00K0Oxo:;;;:;;;,,,,,,,''',,,;;;;;,,'''''''''''..................'''',,;;:::ccllllllllooooooooddddddddxxxxxxdoolc:;,,''..................'',;::cclooddxx
OOOOOOOOOOOOO0000000000000000000000000000KKKKKKKK000koc;;;;;;;,,,,,,,,,,,,,,,;;;;,'''''''''''.................''',,,;;;::cllooooooooodddddddxxxkkkkkkxxxxxxxxddolcc:;,'...................',;:::clooddxx
OOOOOOOOOOOOO000000000000000000000000000KKKKKK0KK0Oxo:;,;;;;;,,,,,,,,,,,,,,,,;;;,'''''''''''................''',,;;::cccllodddddddddxxxxxxxxkkkOOOOOOOkkkxxxxxddoolc:;,'..................'',;:cclodddxx
OOOOOOOOOOOOO00000000000000000000000000KKK000000Okdl:;,,,;;;,,,,,,,,,,,,,,,,;;;,'''''''''''................'',,;;:cclloodddxxxxxxxxxxkkkkkkkkOOOOOOOOOOOkxxxxxddoolc::;,'.................'',;:clloddxxx
OOOOOOOOOOOOO00000000000000000000000000KKK00000Oxoc;;,;;;,,,,,,,,,,,,,,,,,,;;;,''''''''''................'',,;::ccloddxxxxxxxxxxxxxkkkkkkkkOOOOO0000OOOOOOkkxxxddolc:;,''.................',;;::coodxxxx
OOOOOOOOOOOOO00000000000000000000000000000000Okdl:;;;;;;;,,,,,,,,,,,,,,,,;;;,,,'''''''''................',,;:cllooodxxkkkkkkkkkkkkkkkkkkkOOOOOO0000OOOOkkkkkkxxddollc:;,''................',,;::coodxxxk
OOOOOOOO0OOO000000000000000000000000000000000kdlc:;;;;;,,,,,,,,,,,,,,,,,,;;;,,''''''''''..............'',;:clooodxxxkkkkkkkkkkkkkkkkkkkOOOOOOO00000OOOOOkkkkkkxddoolc:;,,'................',,;:clodxxxxx
OOOOOOOO0OOO0000000000000000000000000000000Okdlc:;;;;;;,,,,,,,;,,,,,,,,,,;;,,,,'''''''..............'',;:cloodddxkkkkkkkOOOOOOOOOkkOOOOOOOOOOOOOOOOOOOOOkkkkkkxddoolc::;,''...............',,;:llodxxxkk
OOOOOOOO0OOO000000000000000000000000000000Oxdlc:;;;,,,,,,,,,,,,,,,,,,,,,,,,,,',''''''............',;;;:cloodddxkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkxxxdddolc:::;''..............'',;:clodxxxkkk
OOOOOOO000OOO000000000000000000000000000Okxdoc:;;,,,,,,,,,,,,,,,,,,;,,,,,,,,,'''''''..........'',;:ccclooodddxxkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxdddoolcc::;,'''.............';:clodxxxkkkO
OOOOOOO000OOO00000000000000000000000000Okxdoc:;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''........'',;;:cllloooddddxkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxdddoollc::;;,'''............';:clddxxkkkkk
0000000000OOO0000000000000000000000000Okxdoc:;;;,,,,,,,,,,,,;;;,,,,,,,,,,,,,,,,,,,'......''',;;:ccllooooodddxxkkkOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkxxxdddoollc:::;;,,''............,:lodxxxkkkkk
0000000000OOO000000000000000000000000Oxdooc:;;;,,,,,,,,,,,;;;;,,,;,,,;,,,,,,,,,,,,'.....''',,;:ccllooooodddxxkkkOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkxxxdddoollcc:::;;,'''...........,:lodxxkkkkkk
000000000000000000000000000000000000Oxolcc:;;;,,,,,,,,,,,;;;;;;,,;,,,;,;;;;;;,;;,''.....''',,;:cllooooodddxxkkkOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkxxxxdddoooollcc:::;,,''...........';lodxxxkkkkk
000000000000000000000000000000000OOOxolcc:;;,,,,,,,,,,,,,;;;;;;;;;;;;,,;;;;;;;;;,''.....''',,;:clloooddddxxkkOOOOOOOOOOOOOOOOOOOOOOOOOOkOOkkkkkkkkkkkkkkxxxxxdddooooolcc:::;;,'''...........,coddxxkkkkk
0000000000000000000000000000000000Oxl::::;;,,,,,,,,,,,,,;;:;;;;;;;;;;,,,,,,;;;;;,''.....''',;:cclooddddddxxkkOOOOOOOOOOOOOOOOOOOOOOOOOOkOOkkkkkkkkkkkkkkxxxxxdddooooollcc:::;,,''............:odxxxxxxdo
000000000000000000000000000000000Oxl:::;,,,,,,,,,,,,,,,,;;;;;;;;;;;;,,,;;;;;;;;;,''.....'',,;:clloooooooddxxkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkxxxxxddddoooollcc:::;;,'''...........'cddddolc::
00000000000000000000000KK000000OOxl:;:;,,,,,,,,,,,,,,,,,;;;;;;;;;;;,,,;;;,,;;;;;,,'.....''',;::cccccccllloddxxkkOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkOkkkkkxxxxxxdddoooooollcc::;;,,''............;odoolllox
00000000000000O0000000000K00000Oxc:::,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;,,,;;,,,,;;,,,,'......'',,;::::ccccllllloooddxxkkOOOOOOOOOOOOOOOOOOOOOOOOOkkkkOkkkkkxxxxxxddddooooollcc::;;,,''............,ldoodxkkO
00000000000000O0000000000K0000Oxl::;;,,,,,,,,,,,,,,,,;;;::;;;;;;;;,,,,,,,,,,,,,,,,,'.....'',;::::cccccccllcccccccloddxxkkkOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxxxxddddoooollcc::;;,,''.............cddxxkkkk
00000000000000O00000000000000Oxl:;;,,,,,,,,,,,,,,,,,,;;;;;;;;;,;;,,,,,,,,,,,,,'',,'''''..',;:cllllloooolllcccccc:::cccloddxkkkkOOOOOOOOOOOOOOkkkkkkkkkkkkxxxxxdddddooollcc::;;,,''.............:dxxxkkkk
00000000000000000000000000OOOxl;;,,,,,,,,,,,,,,,,,,,,;:::;;;;;,;;,,,,,,,,'''''''''''''''',;:cloooddddddddddddoollccccccccllodxxkkOkkkkOOOkkkkkkkkkkkkkkkkxxxxxxdddddooolccc:;;,,''.............;dxxxxxxx
0000000000000000000000000OOOxl;;;,,,,,;,,,,,,,,,,,,,,;:::;;;;;,,,,',,,,,'''''''..'''''''',;:cloodddxxxxxxxxxxxxxxxddolllllllloodxxkkkkkkkkkkkkkkkkkkkkkkkxxxxxxdddddooolccc::;;,,''............,oxxxxxxd
00000000000000000000000000Oxc;;;;;;;;;;,,,,,,,,,,,,,;;::;;;;,,,,,''',,,'''''......''''''',;:cloodddxxxxxxxxxxxkkkkkxxddoooooooooddxxkkkkkOkkkkkkkOkkkkkxxxxxxxddddddoollccc::;;,,''............'lddddxxd
0000000000000000000000000Odc:;;,,;;;;;,,,,,,,,,,,,,;;;:;;;;;,,,,'''',,,''''''......''''',;;:cloooddddddxxxxxxxkkkkkkxxxxxxxddddddddxxkkkkOOOkkkkkOkkkkxxxxxxxxdddddooolcccc::;,,'''.............cdxdllcc
00000000OOOOOO0000000000Odc:;;;;;;;;;;,,,,,,,,,,,,,;;;:;;;;,,,,''''''''''''...'......''',,;::ccloodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkOOOOOOOkkkkkkxxxxxddddoollllcc:::::;;,,''''.............cdxxdlc:
00000OOOOOOOOOOOO00000Okoc:;;;,,;,;;;;,,,,,,,,,,,,;;;;;;;,,,,,''''''''''''.............'',;;::cclllooooddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkOOOOOOOOOkkkkxxxxdddoollc:;,,,,,''''''''''''..............:dxkOkxd
00000OOOOOOOOOOOOO000Okdl:;,,,,,,;;;,,,,,,,,,,,,,;;;;;;;;,,,,''''''''''''..............'',,;;::ccclllooddddddddxxxxxxxxxxxxxxxxkkkkOOOOOOOOOOOkkkxxxddddollc::;;,;,,,,'''''.....................;dkOOkkx
00000OOOOOOOOOOOOOO0Okxl:,,,,,',,;;;,,,,,,,,,,,;;;::;;,,,,,''''''''''''''...............''''',,,,;;;;;:::ccllooddddddddddxxxxxxxkkOOOO0OOOOOOkkkxxxddoooollcccc::::::;;;;;;,,''.................;oxkkkOk
OOOOOOO0000OOOOOOOOOOxo:,'',''',;;,,,,,,,,,,,,,;;:::;;,,,,,''''''''''''''.............''.'''....''''.....'''',;;:lloodddddxxxxxxkkOOO00O00OOOkkkxxddooooooolllllllllllllllcc:;,''...............'lkOkOOO
OOOOOOO0000OOOOOOOOkkdc;''''''',;,,,,,,,,,,,,,,;;;:;;,,,,,''''''''''''''..............'''''''''',;;,''...'''''',colccloodddxxxxkkOOO000000OOOkkxxdoooooooooooooooooooooolllcc::;,'...............cxkkOOO
OOOOOOO0OOOOOOOOOkkxdc;,'''''',;,,,,,'',,,,,,,,;;;;;,,,,,'''''''''''''''..........'''''',,;;;;;;;::;;,'......';lxxxolclodxxxxxxkkOOO00000OOOkkxddoooooooooooooooooooooooollcc::;;,'..............;dkkOOO
OOOOOOOOOOOOOOOOOkxdl;'''''''',;,,,'''',,,,,,,,;;;,,,,,,'''''''''''''''...........'''',;;:ccllllcccc::;;,''',coxxxxdlccldxxxxxkOOOO000000OOOkkxdoolloooooooooooooodddooollc::::;;,...............,okkOOO
OOOOOOOOOOOOOOOOkkxo:,'''...'',,'''''''',,,,,,,;;,,,''''''''....''''''...........''',,;:cllooodddddooolllllllodooooolloodkkkkkkOOOO00000OOOkkxdollllooooddoooooooooooollcc:::;;;;'... ...........'lkkkOO
OOOOOOOOOOOOOOOOkxo:,''''..',,,,'''''''''''',,,,,,''''''''''....''''''.........''',,;:clooooodddddddddddddddooddddddddxxkkkkkkkOOOOO0000OOOkkdoollllooodo:;,;;;;;;;:::::::;;;,,,,...  ............cxkkkO
OOOOOOOOOOOOOOOOkdc,''''...',,,''',''''''''',,,,''''''''''''..'''''''''.......'',,;;:cloodddddddxxxxxxxxxxxddddddddddxxxkkkkkOOOOOOOO0OOOOOkxdollclodolc:'...'.....',;,,,;,,,''''..  .............;dkkkO
OOOOOOOOOOOOOOOOxl;'''....'',,,''''''''''''',,,,'''''''''''.''',,''''''.....'',,;::cllooodddddxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkOOOOOOOOOOOOOOkxdolllloooc:;,.........;cl:,''..'''''.................'lxkkk
OOOOOOOOOOOOOOOkdc,'.'....''''''''''''''''''''''.'''''''''.''',,''''...''...',;;::clooddddxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkOOOOOOOOOOOO00Okxdollllloollc:;,'....':lll:;''....'''..................;dxkk
OOOOOOOOOOOOOOkko:,'.'...'''''''''''''''''''''....'''''''''',,,''''........'',,,,;::cloddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkOOOOOOOOOOO00OOOOkxxdolccclooooolllc::;;:cc:;;,,'''..'''........ .........,oxxk
OOOOOOOOOOOOOkkxl;'..'..''''''''''''''...''''''....'''''''',,,''..........'',;;,,,;;:::::clodxxxxxxxxxxxxxxkkkkkkkkkkOOOOOOOOOOOOOOO00OOOOkxxdollllllooooollllllcccc:::;;,,,'''''.......  .........:dxxk
OOOOOOOOOOOOOkkdc,'..'...''''''..'''''....''''.....'''''''',,'..........'',:cccclllllcc::;;::codxxkkkkxxkkkkkkkkkkkOOOOOOOOOOOOOOOOO00OOOOkkxdolllclloooooolllllllllllc:::;;;,,,'.. ..  ...........ckkxx
OOOOOOOOOOOOOOkd:,'......'''.....''''..'''''........''''',,,'..........'';cllllodxxxxxddoollcc:cclodxxkkkkkkkkkkkkkOOOOOO000O000OOOO0000OOkkxxdolllllloooooooollllllllcccc::;;,,'..................:xkdd
OOOOOOOOOOOOOOko;'.....................''''.........''''''''...........,;cllllodxkkkkkkkkkkkxxdolccllodkkkkkkkkkkkOO0000000OOO0000OOOO00OOOkkxdolllllllooooooooooooollllccc::;;,'.................';llcc
OOOOOOOOOOOOOOko;'....................''''.........''''''''..........'';ccccllodxxxkxkkkkOOOOkkkxxdolodxkkkkkkkkkOOO0000000OOOOO000OOOkkkkxxdooolclllllooooooooooooooolllccc::;,... ..............'','',
OOOOOOOOOOOOOOko;'...................'''...........''''''.............',;,,,;;:clclllodkOOOOOOOkkkkkkkkkkOOkkkkkkkOO0000OOOOOOkkxxdolccc:::;,,;;:clllllooooooooooooooooolllcc:,'..  ................,;;'
OOOOOOOOOOOOOOko;'...................''''..........'''''...................',;:cloodxkkOOOOOOOOOOOOkkkkkkkkkkkkkkkkO0OOkkdolc::::;;,,,;;,,''....';clcllloooooooooooooooooolc:,'.... ..  ...........,::,.
OOOOOOOOOOOOOkko;'.................'''''...........''''...''...........'',;:loddxkkkkOkkkxxkkOOOOOOkkkkkkkkkkkxxxxkkxol:;,''',,,;;;;;;;;,''''.....,:lllooodddddodddooooolc:;,,,,'.....  ..........',,''.
OOOOOOOOOOOOOkko;'...............'''''''.................''''''......',,;:lodxxxkkkxxddooodxkOkkOOkkkkkkkkkkxdddddoc;,,''''',;;;:::::;,,''''''.....,cllodddddddddddddolc;;;;::;;'..     ..........''....
kkkOOOOOOOOOOkxo;'..............''''''''.................''',,'.....',;;:coddxxddollccllodxkOOkkOkkkkkkkkkxdddddol:,,;;::::::clollc:;;,,''''''.....':lodddxxxxxdddoolc:;;;;;,'....   .  ................
OOOOOOOOOOOOkxxo:,'.............'''''''''..................'''.......'',,,;:ccc:cclldxxkxxkkkkkkkkkkkkkxxxddooodoc,',;:lolcc:cloddoc:,,,,,,,,''.....':oddxxxxxxxdolllc:;;,,'......  .   ................
OOOOOOOOOOOOkkxoc;'.............'''''''''..................'''............'';:clodxkkkxolodxkkkkkkkkkkxxddddddxxdl;,''',,,,,',;:::::;;,,,,,,,''.......:odxxxxxxxdddol:,;;;;;,,,'..      ................
OOOOOOOOOOOOOkxo:,...............''''......................'...........',;:cldxxkxxdolccloxxkkkkkkxxxxxdddxxkkkkkxo:,'.''''''',,,,,''''',,,,''........,oddxxxxxxxxxdlllllllcc:;'.       ................
OOOOOOOOOOOOOxdc;,................''.......................'.........',;clodxdddolcccclodxkxkkxxxxxdddddxxkOOOOOkkkxoc:;,,;;;,,,;;,'....'''''.........:dddxxxkkkxxkxdddoooolc:;'.       . ..............
OOOOOOOOOOOOkxdc;,.................................................'',,:cloolc::::clodxxxxxxxxxxxxddddxxkOOOOOOOOOOOkkxxddolc:;;::;''...............':oddddxxxkxxxxdoooooollc:,..         ..............
kkkkkkkOOkkkkxo:;'.................................................''',,;,,,;;:cooddxxxxxxxxxxdddddddxkOOOOOOOOOOOOOOOOOOOOkdocc:;,'''.....''...'';:loddddxxxxxxxxoc::::ccccc;'.            ............
kkkkkkkkkkkkkdl;,'.......................................................',;clddxxxxxxxdddxdddooddxkkOOOOOOOOOOOOOOOOOOOOOOOkkxxddlc:;;,;:::::::cloooooddxxxxxxxxxdolc::::;;,..              ...........
kkkkkkkkkkkkxdc;,'.....................................................';:coodxxxxxxddddddooooodxkOOOOOOO00OOOOOOOOOOOOOOOOkkkkxxxxxddddddddoooooooodoodddxxxxxdddddoollc:;,..                ..........
kkkkkkkkkkkxddl;''...................................................';:cloddxxxxxxdddoooolloodxkOOOOOOO0OOOOOOOOOOOOOOOkkkkkkkxxxxxxxxkkxxddoooooooooodddddddddlcclooolc::,..                ..........
kkkkkkkkkOxdddc,....................................................',;:cloddddxxxxxddolllllodxkkkOOOOOOOOOOOOOOOOOOOkkkkkkkxxxxxkkkkkkkkkxdddooooooooooooddddool:;;clllc:;'.                   ........
kkkkkkkkkkdodo:'....................................................',;:clooodddxxxxdoolllccclloddxkkOOOOOOOOOOOOOOOkkkkkkkxxxxxxxxxkkkkkxxdddddoooooooooooooooool:,,:cc:;'.                     .......
kkkkkkkkxdool:,,,'................................  ................',;:cclooddxxxxddoolllllc:;,,:cllllodddddddddddddddddddddooooddddxxxxxdddoooooolllllllllllloooc;,,;;,..                       ... ..
Okkkkkxxddol:,,;;'...............................    ................',;:cclodxxxxddooolooodool:;;:ccccc:;;;;;;;;:::::::::::::cccccclodddddoooooooolllcccccccllllllc;'....                            ..
kOOkkxxxxdl;,,,;,................................    ................',;::cllodddddoooooddxxxxdlc::::lkOOxdddddolc:;;;,,,''''''',,,,,,;;::::::ccllllcc::ccccllooollc:,...                             ..
kkkxxxxdo:,,,,;;'................................    .................',;:cclooodooooooddxxxkkkxoc:::cdxkkkkOKK00Okxxxdlcc::;;,,''......''..''',,::c::::ccllooooolc:;'.                               ..
kxxxxddl;,;;;;;'.....  ..........................    ..................',;:cllooooooodddxkkkkkOOxolc:::::cldk0000000KKK00OOOkxddoolc:;,,,'''''...';::::cclooooolc:;,..
kxdxxoc;:c::;,'......  ..........................    ...................',;:clloooooddxxkkkkkkOOOxdllcccc::cloxkOOkO0KK000000000000Okxxxxdool:,.';:clccllooooolc:;'..
xddxoc;:ll:,,....................................    ....................';:ccloooddddxxkkkkkkOOOOkdoolccc::;;;:looxOO000000OOO0000OOOkOkxoc:;'',:cllllooooolcc:,..
dxxo:;clll:,.....................................    .....................';:cloodddddxxxkkkkkOOOOOkkkdlc:ccc:;;;;;:cloxkkxxkkkkOOkkxdddoc;....,;ccllloooolcc:,..
ddc::clll:'.....................................     ......................';:looddddxxxxkkkkkkkOOOOOOkxoc:::::::;,,,,,;:::clooolllc:;,'......';ccccllooolc:;'.               ..
o:;:lolc:'.......................................      .....................';clooddddxxxkkkkkkkOOOOOOOOkxoc;,,;;,,,,,,''''',;;,,,,,,''......';:cccccclcc:,...                 ...
::coolc,''................   ....................      ......................';clodddddxxkkkkkkkkkkkkkkkkkkxdl:,,'',,,,''''',,,'','''''....';:::cc::cc:;'..
clllc;'.''................   ...................       .......................';:loddddxxkkkkkOkkkkkkkkkkkkkkxdlc:;,,,''''''''''.........';:::::::cc:,...
lll:,'',,.................   ...................        .......................',:loddddxxkkkkkkkkkkkkkkkkkkxxxxddolcc:;;;,,,'''''''',,;::::::::::;,..
lc;,',:;.. .............................. ......        .........................,:clodddxxkkkkkkkkkkkkkkkkkkxxxdddddooolllccccccccccccccc:::::;,..
c,',cc;..................................  ......        .........................';clodddxxkkkkkkkOOkkkkkkkkkxxxdddddddooooooooolllllccc::::;'..
,,,;,......... ..........................    .  .        ..........................',:looddxkkkkkkkkOOkkkkkkkkkkxddddddddddooooooolllllccc:,..
,,'.........        .....................       .        .........................''',:cooddxxkkkkkkOOOOkkkkkkkkxxxxxxxxddddoooooooolllc:;..
,......  ..          ....................                .......................'..'',,;cloddxxkkkOOOkkOkkkkkkkkkxxxxxxxxddddddddooollc:'.
......               ...................                 ......................'''',,,,;;:cloddxxkkkkkkkkkkkkkkkkxxxxxxxdddddoooooolc:,..
.....                 ..................                 ......................'',,;;;;;;;:::clodxxxkkkkkkkkxxxxxxxxdddddddoooolllc:,..
.                    ...................                  .....................',,;;;;;;;:::;::cclodddxxxxxxxxdddddddddooooollcc:;'..
                       ..................                  ...................',,;;;;::::::::::::::cccloooooooooooooooooolllc:;'.... .
                       ..................                 ....................',;;;;;;::::::::::;;;;;:::cccccccccccccccccc:;;,........
                       ..................                 ....................',;;;;;;:::::::::;;;;;;;;;;::::::::c:::::::;;,,'.........                                                            ...
                       ............... ..         .       ...................'',;;:;;;;:;;;;;;;:;;;;;;;;;::::::::c::::::;;;,,'.........                                                          .......
                       ..............   .                 ...................'',;;;;;;;;;;::::::;;;;;;;;;;::::::::::::;;;;;,,'.........                                                            .....
                        .............                     ...................',;;;;;;;:::::::::::::;;;;;;;::::::::::::;;;;;,,'.........
                        ..............                     ..................',;;;;;;;:::::::::::::::::::::::::::::::::;:;;,,''.......
                         ......  ......                    ..................',;;;;;;;:::::::::::::::::::::::::::::::::::;,''''.......
                         ..................                 .................',;;;;;;;::::::::::::::::::::::::::::::::::;;,'''.......
                         ...................                 ................',;,,,;;;:::::::::::::::::::::::::::::::::;;,,'''.......
                         .............   ...                 .................',,,,,;;::::::::::::::::::::::::::::;;;;;;,,''''.......
                         .............    ..                 .................'',,,,;;;;;;;;:::::::::::::::;;;;;;;;;;,,,,''..........
                         .............   ...                  ................'''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,''............
                         ............. .....                   ...............''''',,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'''''.........
                          ............ ....                    ..............'''''',,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'',,''....... .....
                           ...............                     ..............''''',,,,,,,,,,,;;;;;;;;;;;:::::::::::::;;,,,,;,,'''..........
                         .................                     ...............'',,,,,,,,,,,,;;;;;;;;;;:::::::::ccc::::;,;;;;;;,,'..........            .....     ..
                        .................                    .................',,,,,,,,,,,,;;;;;;;;::::::cccccccccccc:;;:::::;;;'...........     ..   ..................
                        ..................                   ................',,,,,,,,,,;;;;;;;;;;::::ccccccccclllllc:;:cclcc:;,'...........   .............................
                        .............. ....                  ................',;;;;;;;;;;;;;;;;;;::::ccclllllllloollc::cclllc:;,,'''....'...  ..................................
                        .......  ..........                 .................,,;;;;;;;;;;;;;;;;;:::::ccllllllooooollcccllllcc:;;;;,'....'... ....................................
                       ........  ..........               ..................',;;;;;;;;;;;;;;;;;:::::cccllooooooddolllclollllc:::::,'.............................................
                       .....     ...........              .................',;;;;;;;;;;;;;;;:::::::ccclllooooddddooollooolc::cc::::,.............................................     ..             ...
                                 ............           ...................,;;;;::::::::;;:::::::::cccllooooddddddoolloool:::clc:cc;'............................................   .....        .......
                                 .............          ...................,;;;:::::::::;:::::::::cccclllooooddoddoolloolc::clcccccc;'................................................... ..... ........
                                ...............      .  ...................,;;::::::::::::::::::::cccccllooooododdolllollcclllccc:cc:,..................................................................
                                ...............      .  ...................,;:::::c::::::::::::::ccccclllooooododdoollllccoddollcccc:;'............................................  ...................
                               .................     .  ...................';::::::::::::::::::ccclllllloooooododoooolc:clodddolllccc:,'........   ................................  .................
                               .................     . ....................';;::::::::::::::::cccllllllloooooooodooodoc:codddddollclcc:,................................................................
                              ..................     .....................',,;:::::::::::::::ccclllllllooooooooooodolc:cloddddddolllcc:,................................................................
                              ..................     ..................'''',,;;;:::::::::::::cclllllllooooooooooodoc::lllooooddddollcc:,...........................................................   ..
                              ..................     ..................'''',,;;;;;;;::::::::ccclllllloooooooooooolcccloooodooodddooolc:,..........................................................     .
                             .....................   .................'''',,;;;::::::::::::cccclllloooooooooooolclllooooooooooodooooll:'..........................................................     .
                             ....   .............    ................'''''',;;::::::::::::cclllllloooooooooddolclooooooooooooooooddooo:'..........................................................     .
                             ...    ..  .........   ................'''''',;;;::::::::::::ccllllllloooooooddllloooodoooooooddooooddddo;...........................................................     .
                                    .   ........    ........... ...'''''.';;;;::::::::::cccllllllloooooolloolloodddddddodddddddoodoodo;'.......................................................  .     .
                                        ........    ...................',,;:::::::::::::cclllllollloooollllloooodddddddddddddddddddddl;'........................................................       .
                                    ...........    ....................,;::::::::::::cccclllllooollooolllllooddddddddddddddddddddddxdl,'...................................................... .       .
                          ......  .............    ..................';:::::;;::::cccccclllllooloodollloooodddddddddxxxxddddddddxxxxdc,'........................................................      ..
                          .....................    .................,;;::::;;::ccccccccllllloooodddoooooodddddddddxxxxxxdddddddxxxxxo:''........................................................      ..
                          .....................    ........''......,;;;;::::::cccccccccllllooooddolloodddddddddddxxxxxxxxxxdxxxxxxxxo;'''.................................................. ..        ..
                         ....................    .......'''.....'',,,,;;::c::ccccccccllllllooolllllooodddddddddddxxxxxxxxxxxxxxxxxxxl,'''...............................................              ..
                          ......'''''''.....    .......''....',;;::;,,;;::ccccccccccccllloollcclloodddddddddddddxxxxxxxxxxxxxxxxxxxdc,''...............................................               ..
                         .....'','''''''....    ...........',;::::cc::;;:::::cccccc::clllllccllooddddddxxxxxxxxxxxxxxxxxxxxxxxkxkxxdc'...'............................................                ..
                        .....'''',,'''''...    .........',;::ccclccccccc:::;::::::::;::clccloodddddddddxxxxxxxxxxxxxxxxxxxxxxxxkxxxd:'............................................                     .
                       ......'''''''.......     .....'',,;:ccccllcccccccccc:;;;;;:clc::;,;cloodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxo:'............................................
                     ...   ....'''........     .....',,,;::ccccccccccccccllc:cclccclc:;;;:looddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdl;'''..........................................
                     ...    .............    ......'',;;:::cccccccccccccccccclllolllooccllodddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxkxdc,''...........................................
                              ............  .....''',;:::ccccccllllccccllcllllodddodkxolclodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxkkdc,''...........................................
                              ....'....    ...'''',;;:ccccccccclllllllllllllldkkxxxkkxxolodxxxxxxxxxxxxxxxxkkkxxxxxxxxxxxxxxxxxxxkd:''............................................
                             ....''...    ...''',;:::::ccccccccllllllllllllldxkO0KKK0kOxodxxxxxxxxxxxxxxxxxkkkxxxxxxxxxxxxxxxxxxxxo;''............................................
                             ........    ...'''';:c::::ccccccccccllllllllllodkk0KKKK0OOkddxxxxxxxxkkkkxxxxxkkkxxxkkkxxxxxxxxxxxxkxo,..............................................
                             ........   ...'''',;:::::cccccccccccccclllloooodxxO0K000OOkdxxxxxxxxxxxxxxxxxxkkkxxxkkxxxxxxxxxxxxxkxc,..............................................
                                ....   ..'',',;;::::::cccccccccccclllloooooodxxxxkkkOOxdxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkxc'.............................     ...........
                                 .   ...'',,,;:::::::::ccccccccccclllloooooddddxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd;...............................      ...   ...
                                    ...'''',,;::::::::::ccccccccccllloooddddxxxxxkxxxxkkkkxxxxkkxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl,...............................
                                   ....''',,;;::::::::::ccccccccllllooodddddxxxxxxxxxxxkkkxxxxkxxxxxxxxxxxxxxxxxxkkkxxxxxxxxxxxxdc,..............................
                                   ...'',,,;;;;::::::::ccccccclllloooodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkxxxxxxxxxxxxxdc'..............................
                                   ...'',,;;;;;;;::::::cccccccllllooodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd:'...............................
                                   ....',,;;;;;:::::::::cccccllllloooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd:............................. ..
                                   .....',,;;;;:::::::::ccccccllllooooodddddxxdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo;.............................
                                     .....',,;;:::::::::cccccccclllooooddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo;............................
                                       .....'',;;;:::::::ccccccllllllooooodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo,............................
                                    ..........',,;;:::::::ccccclccclllllooodddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl,...........................
                                   .............'',,;;;;;:::cccccccllllloooooddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxdddddc'..........................
                                   ................'',,;;;;:::::::cccccllooooodddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxdo:'.......................
                            .........................'''',,,;;::::::cccccllllooodddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdlc;'.......................
                            ................................'',,;;;:::ccccclllooooddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdoc,''.........................
                            .... ..............................''',,;:::::ccccllooooddddddddddddddxxxxxxxxxxxxxxxxxxddolc;'............................
                            ....  ..................................'',,;;:ccccllllooodddddddddddddddxxxxxxxxxxddddoc:,'..............................
                          ......  .....................................'';:ccccllllooooddddddddddddddxxxxxxxxxddolc;'.................... ..... ........
"

echo "$nadia"
