cursor:
  style:
    shape: Beam
    blinking: Off
  vi_mode_style:
    shape: Beam
    blinking: Off

colors:
  primary:
    foreground: '#F3BA81'
    background: '#131313'

font:
  size: 12.0

window:
  opacity: 0.1
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: None

