[cursor]
	style = { shape = "Beam", blinking = "Off" }
	vi_mode_style = { shape = "Beam", blinking = "Off" }

[colors]
	[colors.primary]
		foreground = "#F3BA81"
		background = "#131313"

[font]
	size = 12.0

[window]
	padding = {x = 5, y = 5}
	dynamic_padding = true
	decorations = "None"

