cursor:
  style:
    shape: Beam
    blinking: Off
  vi_mode_style:
    shape: Beam
    blinking: Off

colors:
  primary:
    foreground: '#D0D0D0'
    background: '#000000'

font:
  normal:
    family: "MesloLGSDZNerdFont"
window:
  opacity: 0.1
  padding:
    x: 5
    y: 5
  dynamic_padding: false
  decorations: None
  term: xterm-256color
