call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-commentary'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'dense-analysis/ale'
Plug 'reedes/vim-lexical'
Plug 'lervag/vimtex'
Plug 'preservim/tagbar', { 'on': 'TagbarToggle' }

call plug#end()
syntax enable
colorscheme slate
filetype plugin indent on

set spell spelllang=es
set completeopt=menu,menuone,noselect
set termguicolors
set history=500
set encoding=utf-8
set scrolloff=8
set list listchars=tab:»·,trail:·
set foldmethod=syntax
set foldlevel=0
set cursorline
set backspace=2
set autoread
set incsearch
set clipboard=unnamedplus
set lazyredraw
set updatetime=300
set mouse=a
set laststatus=4
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

let &t_ut=''

let g:loaded_python_provider = 1
let g:loaded_python3_provider = 1

let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'
let g:ale_set_statusline = 1
let g:ale_set_highlights = 1
let g:ale_virtualtext_cursor = 1

let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_compiler_latexmk = {
      \ 'build_dir' : '',
      \ 'callback' : 1,
      \ 'continuous' : 1,
      \}
let g:vimtex_quickfix_mode = 0

nnoremap <C-Down> ]s
nnoremap <C-Up> [s
nnoremap <C-Left> z=
nnoremap <Leader>q :cclose<CR>

autocmd BufNewFile *.c,*.h 0r ~/.vim/templates/template.c
autocmd BufNewFile *.cpp,*.hpp 0r ~/.vim/templates/template.cpp
autocmd BufNewFile *.ino 0r ~/.vim/templates/template.ino
autocmd BufNewFile *.tex 0r ~/.vim/templates/template.tex
autocmd BufNewFile *.h 0r ~/.vim/templates/template.h

autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=blue   ctermbg=234
autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=green  ctermbg=234
autocmd Syntax tex,c,cpp,vim,xml,html,xhtml setlocal foldmethod=syntax
autocmd Syntax tex,c,cpp,vim,xml,html,xhtml,perl normal zR

inoremap ( ()<Left>
inoremap { {}<Left>
inoremap [ []<Left>
inoremap ' ''<Left>
inoremap " ""<Left>
inoremap $ $$<Left>
inoremap <C-Left> <C-X><C-S>
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<C-g>u\<CR>"
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<CR>"

highlight Type cterm=italic gui=italic
highlight Function cterm=italic gui=italic
highlight Constant cterm=bold gui=bold
highlight Normal ctermbg=NONE guibg =#131313
highlight texStatement guifg=#FF5733 gui=bold
highlight texCmdPart guifg=#C70039 gui=italic
highlight String guifg=#FFA07A gui=italic
